# Numpy Practice

In [2]:
# install numpy (pip install numpy)
import numpy as np

# Creating an array

In [3]:
# 1-D Array
names = np.array(['ali','umar','mohsin'])
names

array(['ali', 'umar', 'mohsin'], dtype='<U6')

In [5]:
scores = np.array([3,4,5])
scores

array([3, 4, 5])

In [6]:
type(names)

numpy.ndarray

In [7]:
len(names)

3

In [11]:
# indexing 
names[2]
scores[0:] # to get full array

array([3, 4, 5])

In [12]:
scores.mean()

4.0

In [14]:
# zero array
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.empty(5)

array([2.12199579e-314, 4.67296746e-307, 3.69561103e-321, 1.38354126e-311,
       0.00000000e+000])

In [18]:
# range 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# specify the range 
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# specify the interval of range function
np.arange(3,33,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [23]:
# The numpy.linspace() function returns number spaces evenly w.r.t interval. Similar to numpy.arange() function but instead of step it uses sample number. 
# Syntax  numpy.linspace(start,
            #    stop,
            #    num = 50,
            #    endpoint = True,
            #    retstep = False,
            #    dtype = None)
# -> start  : [optional] start of interval range. By default start = 0
# -> stop   : end of interval range
# -> restep : If True, return (samples, step). By default restep = False
# -> num    : [int, optional] No. of samples to generate
# -> dtype  : type of output array
np.linspace(1,80, num= 4)

array([ 1.        , 27.33333333, 53.66666667, 80.        ])

In [25]:
# specify the data type
np.ones(50, dtype=np.int64 )

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [26]:
np.ones(50, dtype=np.float64 )

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Functions

In [29]:
a = np.array([10,9,8,7,6,5,67,98,0.4,2.9])
a

array([10. ,  9. ,  8. ,  7. ,  6. ,  5. , 67. , 98. ,  0.4,  2.9])

In [34]:
a.sort()
a

array([ 0.4,  2.9,  5. ,  6. ,  7. ,  8. ,  9. , 10. , 67. , 98. ])

In [36]:
b = np.array([10,8,90,6,5,4,92,65])
b

array([10,  8, 90,  6,  5,  4, 92, 65])

In [38]:
c = np.concatenate((a,b))

In [40]:
c.sort()
c

array([ 0.4,  2.9,  4. ,  5. ,  5. ,  6. ,  6. ,  7. ,  8. ,  8. ,  9. ,
       10. , 10. , 65. , 67. , 90. , 92. , 98. ])

# 1D-Array

In [4]:
numpy_1d = np.array([3,2,4,5])
numpy_1d.ndim

1

# 2-D Arrays

In [6]:
# numpy only store same data type
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(a)
a.ndim

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


2

In [8]:
b = np.array([[4,5,7,6,5], [6,7,3,4,5]])
b

array([[4, 5, 7, 6, 5],
       [6, 7, 3, 4, 5]])

In [11]:
c = np.concatenate((a,b), axis=1)
c

array([[ 1,  2,  3,  4,  5,  4,  5,  7,  6,  5],
       [ 6,  7,  8,  9, 10,  6,  7,  3,  4,  5]])

In [12]:
x = np.concatenate((a,b), axis=0)
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 4,  5,  7,  6,  5],
       [ 6,  7,  3,  4,  5]])

In [4]:
fake_array = np.random.rand(4)
fake_array

array([0.02693482, 0.02876371, 0.01508027, 0.46226351])

In [6]:
fake_array * 4

array([0.10773926, 0.11505484, 0.06032109, 1.84905406])

In [9]:
fake_array + fake_array
fake_array

array([0.10773926, 0.11505484, 0.06032109, 1.84905406])

In [10]:
# matrix

np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])